version: 2
registries:
  docker-registry-gcr-io:
    type: docker-registry
    url: https://gcr.io
    username: _json_key
    password: "${{secrets.DOCKER_REGISTRY_GCR_IO_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sgammon
  assignees:
  - sgammon
  labels:
  - dependencies
  - node
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: "@bazel/ibazel"
    versions:
    - 0.14.0
    - 0.15.6
    - 0.15.8
    - 0.15.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: jasmine
    versions:
    - 3.6.4
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sgammon
  assignees:
  - sgammon
  labels:
  - dependencies
  - submodules
- package-ecosystem: pip
  directory: "/tools"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/images/base/alpine"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sgammon
  assignees:
  - sgammon
  labels:
  - dependencies
  - docker
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  registries:
  - docker-registry-gcr-io
- package-ecosystem: docker
  directory: "/images/base/node"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sgammon
  assignees:
  - sgammon
  labels:
  - docker
  - node
  - dependencies
  registries:
  - docker-registry-gcr-io
- package-ecosystem: docker
  directory: "/images/ci"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - sgammon
  assignees:
  - sgammon
  labels:
  - dependencies
  - docker
  registries:
  - docker-registry-gcr-io
