
FROM us-docker.pkg.dev/cookies-eng/public/base/gitpod:latest

ENV SHELL=zsh \
    C6S_CODESPACES_VERSION=v1a \
    HOME=/home/gitpod \
    DEVCONTAINER=yes

RUN echo "Installing BuildBuddy credentials..." \
        && echo "$BUILDBUDDY_CERT" > /home/dev/buildbuddy-cert.pem \
        && echo "$BUILDBUDDY_KEY" > /home/dev/buildbuddy-key.pem;

COPY defs/container.bazelrc /home/gitpod/.bazelrc

